eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-primary:8011/,http://eureka-secondary:8012/,http://eureka-tertiary:8013/

---
spring:
  profiles: subject
words: Yo,Tu,El,Ella,Esto

---
spring:
  profiles: verb
words: corrió, sabía, tenía, vió, compró

---
spring:
  profiles: article
words: un,una,la

---
spring:
  profiles: adjective
words: razonable, permeable, sospechoso, ordinario, improbable

---
spring:
  profiles: noun
words: barco, libro, voto, asiento, mochila, partición
